environment: test
repoPrefix: "theanh0906"
servicePort: 80
replicaCount: 1

services:
  - appName: pems-fe
    type: NodePort
    port: 80
    nodePort: 30001
    image: 
      repository: pems_fe
      tag: r1.0.3
  - appName: pems-be
    type: NodePort
    port: 80
    nodePort: 30002
    image: 
      repository: pems_be
      tag: r1.0.2
