{{- range $services := .Values.services }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $services.appName }}
  labels:
    app: {{ $services.appName }}
spec:
  replicas: {{ $.Values.replicaCount }}
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: {{ $services.appName }}
  template:
    metadata:
      labels:
        app: {{ $services.appName }}
    spec:
      containers:
      - name: {{ $services.appName }}
        {{- if and $services.image $services.image.tag}}
        image: {{ $.Values.repoPrefix }}/{{ $services.appName }}:{{ $services.image.tag }}
        {{- else}}
        image: {{ $.Values.repoPrefix }}/{{ $services.appName }}:{{ $.Values.imageDefaultTag }}
        {{- end}}
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 5
          httpGet:
            {{- if $services.healthCheckPath}}
            path: {{ $services.healthCheckPath }}
            {{- else}}
            path: {{ $.Values.defaultHealthCheckPath }}
            {{- end}}
            {{- if $services.port}}
            port: {{ $services.port }}
            {{- else}}
            port: {{ $.Values.deploymentPort }}
            {{- end}}
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        ports:
        {{- if $services.port}}
        - containerPort: {{ $services.port }}
        {{- else}}
        - containerPort: {{ $.Values.deploymentPort }}
        {{- end}}
        readinessProbe:
          failureThreshold: 3
          httpGet:
            {{- if $services.healthCheckPath}}
            path: {{ $services.healthCheckPath }}
            {{- else}}
            path: {{ $.Values.defaultHealthCheckPath }}
            {{- end}}
            {{- if $services.port}}
            port: {{ $services.port }}
            {{- else}}
            port: {{ $.Values.deploymentPort }}
            {{- end}}
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: {{ $.Values.environment }}
        - name: DOTNET_ENVIRONMENT
          value: {{ $.Values.environment }}
        - name: APPLICATION_CODE
          value: {{ $services.appName }}
        - name: APPLICATION_BASE_PATH
          value: {{ $.Values.prefixPath }}{{ $services.subPath }}
        - name: DOTNET_RUNNING_IN_CONTAINER
          value: "true"
        {{- if $services.port}}
        - name: ASPNETCORE_HTTP_PORTS
          value: "{{ $services.port }}"
        {{- else}}
        - name: ASPNETCORE_HTTP_PORTS
          value: "{{ $.Values.deploymentPort }}"
        {{- end}}
        {{- if $services.env}}
        {{- $services.env | toYaml | nindent 8 }}
        {{- end}}
---
{{- end }}

{{- range $workers := .Values.workers }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $workers.appName }}
  labels:
    app: {{ $workers.appName }}
spec:
  replicas: {{ $.Values.replicaCount }}
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: {{ $workers.appName }}
  template:
    metadata:
      labels:
        app: {{ $workers.appName }}
    spec:
      containers:
      - name: {{ $workers.appName }}
        {{- if and $workers.image $workers.image.tag}}
        image: {{ $.Values.repoPrefix }}/{{ $workers.appName }}:{{ $workers.image.tag }}
        {{- else}}
        image: {{ $.Values.repoPrefix }}/{{ $workers.appName }}:{{ $.Values.imageDefaultTag }}
        {{- end}}
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 5
          httpGet:
            {{- if $workers.healthCheckPath}}
            path: {{ $workers.healthCheckPath }}
            {{- else}}
            path: {{ $.Values.defaultHealthCheckPath }}
            {{- end}}
            {{- if $workers.port}}
            port: {{ $workers.port }}
            {{- else}}
            port: {{ $.Values.deploymentPort }}
            {{- end}}
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        ports:
        {{- if $workers.port}}
        - containerPort: {{ $workers.port }}
        {{- else}}
        - containerPort: {{ $.Values.deploymentPort }}
        {{- end}}
        readinessProbe:
          failureThreshold: 3
          httpGet:
            {{- if $workers.healthCheckPath}}
            path: {{ $workers.healthCheckPath }}
            {{- else}}
            path: {{ $.Values.defaultHealthCheckPath }}
            {{- end}}
            {{- if $workers.port}}
            port: {{ $workers.port }}
            {{- else}}
            port: {{ $.Values.deploymentPort }}
            {{- end}}
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: {{ $.Values.environment }}
        - name: DOTNET_ENVIRONMENT
          value: {{ $.Values.environment }}
        - name: APPLICATION_CODE
          value: {{ $workers.appName }}
        - name: APPLICATION_BASE_PATH
          value: {{ $.Values.prefixPath }}{{ $workers.subPath }}
        - name: DOTNET_RUNNING_IN_CONTAINER
          value: "true"
        {{- if $workers.port}}
        - name: ASPNETCORE_HTTP_PORTS
          value: "{{ $workers.port }}"
        {{- else}}
        - name: ASPNETCORE_HTTP_PORTS
          value: "{{ $.Values.deploymentPort }}"
        {{- end}}
        {{- if $workers.env}}
        {{- $workers.env | toYaml | nindent 8 }}
        {{- end}}
---
{{- end }}