apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pems-{{ $.Values.environment }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
spec:
  rules:
  - host: {{ $.Values.hostIngress }}
    http:
      paths:
      {{- range $services := .Values.services }}
      - path: {{ $.Values.prefixPath }}{{ $services.subPath }}
        pathType: Prefix
        backend:
          service:
            name: {{ $services.appName }}-svc
            port:
              number: {{ $.Values.servicePort }}
      {{- end }}