{{- range $services := .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $services.appName }}-svc
  labels:
    app: {{ $services.appName }}-svc
spec:
  type: {{ $services.type }}
  ports:
    - port: {{ $.Values.servicePort }}
      targetPort: {{ $services.port }}
      protocol: TCP
      name: http
      {{- if $services.nodePort }}
      nodePort: {{- $services.nodePort }}
      {{- end }}
  selector:
    app: {{ $services.appName }}
---    
{{- end }}
