{{- range $services := .Values.services }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $services.appName }}
  labels:
    app: {{ $services.appName }}
spec:
  replicas: {{ $.Values.replicaCount }}
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: {{ $services.appName }}
  template:
    metadata:
      labels:
        app: {{ $services.appName }}
    spec:
      containers:
      - name: {{ $services.appName }}
        {{- if $services.image.tag}}
        image: {{ $.Values.repoPrefix }}/{{ $services.appName }}:{{ $services.image.tag }}
        {{- else}}
        image: {{ $.Values.repoPrefix }}/{{ $services.appName }}:{{ $.Values.imageDefaultTag }}
        {{- end}}
        imagePullPolicy: IfNotPresent
        ports:
        {{- if $services.port}}
        - containerPort: {{ $services.port }}
        {{- else}}
        - containerPort: {{ $.Values.deploymentPort }}
        {{- end}}
        {{- if $services.env}}
        env: {{ $services.env | toYaml | nindent 8 }}
        {{- end}}
---
{{- end }}